version: '3.8'

volumes:
  chat_bot_data:
    driver: local

networks:
  default:
    name: chat_bot
    external: false

services:
  chat_bot:
    container_name: chat_bot
    build: .
    image: chat_bot-v1
    env_file:
      - .env
    depends_on:
      - openai
    ports:
      - "80:80"
    volumes:
      - chat_bot_data:/app
    entrypoint: "./docker-entrypoint.sh"
    restart: always

  openai:
    container_name: openai
    image: hlohaus789/g4f:latest
    ports:
      - "8080:8080"
      - "1337:1337"
      - "7900:7900"
    shm_size: "2g"
    restart: always

# docker run --net=host -it -e NGROK_AUTHTOKEN=2fmaTYip56StKwzSTlfMIVcZYkM_2i57Fs8jZxDXrcQQZ3CMP ngrok/ngrok:latest http 80